packages:
  - '.'
  - 'poc'

allowBuilds:
  esbuild: true
ignoredBuiltDependencies:
  - esbuild
minimumReleaseAgeExclude:
  - '@pkgr/core@0.3.6'
  - eslint-plugin-prettier@5.5.6
  - synckit@0.11.13
  - googleapis@173.0.0
  - '@eslint/plugin-kit@0.7.2'
  - '@inquirer/ansi@2.0.7'
  - '@inquirer/checkbox@5.2.1'
  - '@inquirer/confirm@6.1.1'
  - '@inquirer/core@11.2.1'
  - '@inquirer/editor@5.2.1'
  - '@inquirer/expand@5.1.1'
  - '@inquirer/external-editor@3.0.2'
  - '@inquirer/figures@2.0.7'
  - '@inquirer/input@5.1.1'
  - '@inquirer/number@4.1.1'
  - '@inquirer/password@5.1.1'
  - '@inquirer/prompts@8.5.1'
  - '@inquirer/rawlist@5.3.1'
  - '@inquirer/search@4.2.1'
  - '@inquirer/select@5.2.1'
  - '@inquirer/type@4.0.7'
  - eslint@10.4.1
  - fuse.js@7.4.0
  - '@inquirer/editor@5.2.2'
  - '@inquirer/external-editor@3.0.3'
  - '@inquirer/input@5.1.2'
  - '@inquirer/prompts@8.5.2'
  - '@vitest/coverage-istanbul@4.1.8'
  - '@vitest/expect@4.1.8'
  - '@vitest/mocker@4.1.8'
  - '@vitest/pretty-format@4.1.8'
  - '@vitest/runner@4.1.8'
  - '@vitest/snapshot@4.1.8'
  - '@vitest/spy@4.1.8'
  - '@vitest/ui@4.1.8'
  - '@vitest/utils@4.1.8'
  - tsx@4.22.4
  - vitest@4.1.8
  - '@typescript-eslint/eslint-plugin@8.60.1'
  - '@typescript-eslint/parser@8.60.1'
  - '@typescript-eslint/project-service@8.60.1'
  - '@typescript-eslint/scope-manager@8.60.1'
  - '@typescript-eslint/tsconfig-utils@8.60.1'
  - '@typescript-eslint/type-utils@8.60.1'
  - '@typescript-eslint/types@8.60.1'
  - '@typescript-eslint/typescript-estree@8.60.1'
  - '@typescript-eslint/utils@8.60.1'
  - '@typescript-eslint/visitor-keys@8.60.1'
  - typescript-eslint@8.60.1
