export const API_CONSTANTS = {
  GOOGLE_PEOPLE_API: {
    VERSION: 'v1',
    PAGE_SIZE: 1000,
    DISPLAY_PAGE_SIZE: 15,
    TOP_CONTACTS_DISPLAY: 10,
    RATE_LIMIT_READ: 300,
    RATE_LIMIT_WRITE: 60,
    RATE_LIMIT_DAILY: 1_000_000,
    BROWSER_TIMEOUT: 240000,
    REQUEST_TIMEOUT: 30000,
    MAX_RETRIES: 5,
    RETRY_BASE_DELAY: 1000,
    RETRY_MAX_DELAY: 16000,
    MAX_FIELD_LENGTH: 1024,
    MAX_FIELDS_PER_CONTACT: 500,
  },
  SCOPES: ['https://www.googleapis.com/auth/contacts'],
};
