export const EMOJIS = {
  STATUS: {
    SUCCESS: '✅',
    ERROR: '❌',
    WARNING: '⚠️',
    INFO: 'ℹ️',
    IMPORTANT: '🚨',
  },
  NAVIGATION: {
    EXIT: '🚪',
    BACK: '🔙',
    GO_BACK: '⬅️',
    SKIP: '⏭️',
    SKIP_ARROW: '➡️',
  },
  ACTIONS: {
    ADD: '➕',
    EDIT: '✏️',
    DELETE: '🗑️',
    SEARCH: '🔍',
    PROCESS: '▶️',
    SYNC: '🔄',
    CLEANUP: '♻️ ',
  },
  FIELDS: {
    COMPANY: '🏢',
    PERSON: '👤',
    JOB_TITLE: '💼',
    EMAIL: '📧',
    PHONE: '📞',
    LINKEDIN: '🔗',
    LABEL: '🏷️',
    GROUP: '👥',
  },
  DATA: {
    INDEX: '🔢',
    ID: '🆔',
    REASON: '⁉️',
    CLIPBOARD: '📋',
  },
  SCRIPTS: {
    DEFAULT: '📄',
    CONTACTS_SYNC: '🔄',
    EVENTS_JOBS: '📝',
    HIBOB: '📇',
    LINKEDIN: '🔗',
    OTHER_CONTACTS: '🗄️ ',
    SMS_WHATSAPP: '💬',
    STATISTICS: '📊',
  },
  MENU: {
    WRITE_NOTES: '📓',
    CREATE_NOTE: '📝',
    REWRITE_NOTE: '📋',
    FOLDER: '📁',
    CREATE_LABEL: '🏷️',
  },
  AUTH: {
    LOCK: '🔐',
    SECURITY: '🔒',
  },
  API: {
    READ: '📖',
    WRITE: '✏️',
  },
  SHELL: {
    BUILD: '🏗️',
    TEST: '🧪',
    COMPLETE: '✨',
    STEP: '📝',
  },
} as const;
