export enum MaintainerIssueType {
  CONTAINS_HEBREW = 'CONTAINS HEBREW',
  EMPTY_NAME = 'EMPTY NAME',
  EMPTY_CONTACT = 'EMPTY CONTACT',
  DUPLICATE_CONTACTS = 'DUPLICATE CONTACTS',
  POSSIBLE_DUPLICATE_CONTACT = 'POSSIBLE DUPLICATE CONTACT',
  MISSING_LABEL = 'MISSING LABEL',
  WRONG_LABEL = 'WRONG LABEL',
  MISSING_PHONE_EMAIL_LABEL = 'MISSING PHONE/EMAIL LABEL',
  INVALID_PHONE_EMAIL_LABEL = 'INVALID PHONE/EMAIL LABEL',
  PHONE_LABEL_NOT_MATCH_TO_COMPANY_NAME = 'PHONE LABEL NOT MATCH TO COMPANY NAME',
  EMAIL_LABEL_NOT_MATCH_TO_COMPANY_NAME = 'EMAIL LABEL NOT MATCH TO COMPANY NAME',
  PHONE_CONTAINS_SEPARATORS = 'PHONE CONTAINS SEPARATORS',
  MISSING_URL_LABEL = 'MISSING URL LABEL',
  INVALID_URL_LABEL = 'INVALID URL LABEL',
  DUPLICATE_PHONE_GLOBAL = 'DUPLICATE PHONE - GLOBAL',
  DUPLICATE_PHONE_SINGLE = 'DUPLICATE PHONE - SINGLE',
  DUPLICATE_EMAIL_GLOBAL = 'DUPLICATE EMAIL - GLOBAL',
  DUPLICATE_EMAIL_SINGLE = 'DUPLICATE EMAIL - SINGLE',
  DUPLICATE_URL_GLOBAL = 'DUPLICATE URL - GLOBAL',
  DUPLICATE_URL_SINGLE = 'DUPLICATE URL - SINGLE',
  MISSING_REQUIRED_URL_FOR_LABEL = 'MISSING REQUIRED URL FOR #LABEL#',
  INVALID_URL = 'INVALID URL',
  PHONE_GLOBAL_PREFIX = 'PHONE GLOBAL PREFIX',
  PHONE_CONTAIN_SPACES = 'PHONE_CONTAIN_SPACES: #VALUE#',
  OUTDATED_COMPANY_NAME = 'OUTDATED COMPANY NAME - SHOULD BE: #FIXED#',
  INVALID_NAME = 'INVALID NAME - SHOULD BE: #FIXED#',
  INVALID_CONTACT_NAME = 'INVALID CONTACT - Name: #FIXED#',
  INVALID_CONTACT_COMPANY = 'INVALID CONTACT - Company: #FIXED#',
  NOTES_CONTAINS_BREAK_LINES = 'NOTES CONTAINS BREAK LINES',
  CONTAINS_WHITE_SPACES = 'CONTAINS WHITE SPACES IN FIELDS: #FIELDS#',
  OTHER_CONTACT = 'OTHER CONTACT',
  POSSIBLE_DUPLICATE_CONTACTS_BY_NOTES = 'POSSIBLE DUPLICATE CONTACTS BY NOTES',
  LOWER_CASE_NAME = 'LOWER CASE NAME',
  UPPER_CASE_NAME = 'UPPER CASE NAME',
  CONTAINS_HIDDEN_UNICODE_CHARACTER = 'CONTAINS_HIDDEN_UNICODE_CHARACTER',
  MISSING_SUB_LABEL = 'MISSING SUB-LABEL FOR: #LABEL#',
  INVALID_ORDER_FOR_SUB_LABEL = 'INVALID ORDER FOR SUB-LABEL',
  INVALID_MIXED_LABELED = 'INVALID MIXED LABELED',
  INVALID_LABEL = 'INVALID LABEL',
  INVALID_LABEL_NAME = 'INVALID LABEL NAME - SHOULD BE: #FIXED#',
  CONTAINS_MULTIPLE_SPACES = 'CONTAINS MULTIPLE SPACES IN FIELD: #FIELD#',
  INVALID_EMAIL = 'INVALID EMAIL',
}

export interface MaintainerException {
  name?: string;
  url?: string;
  reason: string;
}

export interface MaintainerReportItem {
  contact: {
    firstName: string;
    lastName: string;
    resourceName?: string;
    fullName: string;
    label: string;
    phones: { number: string; label: string }[];
    emails: { value: string; label: string }[];
    websites: { url: string; label: string }[];
    company: string;
    jobTitle: string;
    biography: string;
  };
  issues: MaintainerIssueType[];
  customIssueMessages?: Partial<Record<MaintainerIssueType, string>>;
  duplicateDetails?: Partial<
    Record<
      MaintainerIssueType,
      { value: string; otherContacts: { id: string; name: string }[] }[]
    >
  >;
}
