export class RegexPatterns {
  static readonly HEBREW = /[\u0590-\u05FF]/;
  static readonly EMAIL = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
  static readonly EMAIL_CONSECUTIVE_DOTS = /\.\./;
  static readonly EMAIL_LEADING_DOT = /^\./;
  static readonly EMAIL_TRAILING_DOT = /\.@/;
  static readonly PHONE = /^[\d+\-\s()]+$/;
  static readonly PHONE_NON_DIGITS = /[\s\-()]/g;
  static readonly LABEL_NAME = /^[a-zA-Z0-9\s\-_]+$/;
  static readonly MULTIPLE_SPACES = /\s+/;
  static readonly NUMBER_GROUPING = /\B(?=(\d{3})+(?!\d))/g;
  static readonly MIXED_CONTENT = /[a-zA-Z0-9]/;
  static readonly PHONE_ALLOWED_CHARS = /^[\d+\-\s()#*]+$/;
  static readonly PHONE_ONLY_SPECIAL = /^[\s\-+()#*]+$/;
  static readonly DIGITS_ONLY = /[^\d]/g;
  static readonly LINKEDIN_PROTOCOL = /^https?:\/\//;
  static readonly LINKEDIN_SUBDOMAIN = /^(www\.|m\.)/;
  static readonly LINKEDIN_PREFIX = /^linkedin\.com\//;
  static readonly LINKEDIN_TRAILING_SLASH = /\/$/;
  static readonly LINKEDIN_PROFILE_SLUG = /in\/([^/]+)/;
  static readonly LINKEDIN_PROFILE_PATH = /\/in\//;
  static readonly LINKEDIN_COMPANY_PATH = /\/company\//;
  static readonly COMPANY_NAME_SEPARATORS = /[,|\-]|\s{2,}/;
  static readonly CAMEL_CASE_SPLIT = /(?=[A-Z])/;
  static readonly PHONE_NORMALIZE = /[\s\-()#*]/g;
  static readonly ISO_TIMESTAMP_COLONS = /[:.]/g;
  static readonly PORT_PID_WINDOWS = /\s+(\d+)\s*$/;
  static readonly SYNCER_ADDED_NOTE = /Added by the people syncer script( \([^)]+\))?/;
  static readonly SYNCER_UPDATED_NOTE = /Updated by the people syncer script( \([^)]+\))?/;
  static readonly SYNC_ADDED_NOTE = /Added by the contacts sync script/;
  static readonly SYNC_UPDATED_NOTE = /Updated by the contacts sync script/;
  static readonly SYNCER_NOTE_DATE = /Last update: (\d{2}\/\d{2}\/\d{4}(?: \d{2}:\d{2}:\d{2})?)/;
  static readonly DATE_DD_MM_YYYY = /(\d{2})\/(\d{2})\/(\d{4})(?: (\d{2}):(\d{2}):(\d{2}))?/;
  static readonly PHONE_UNIVERSAL = /^[+]?[(]?[0-9]{1,4}[)]?[-\s./0-9]*$/;
  static readonly PHONE_EXTRACTION = /\+?\d{1,4}[\s\-.]?\(?\d{1,4}\)?[\s\-.]?\d{1,4}[\s\-.]?\d{1,9}(?:\s*(?:ext|x|extension)\.?\s*\d+)?/gi;
  static readonly PHONE_SHORT_CODE = /^[*#]\d{2,6}$/;
  static readonly PHONE_VANITY = /\d{3,}[A-Za-z]+|\+?\d[\d\-\s()]*[A-Za-z]+[\d\-\s()A-Za-z]*/;
  static readonly PHONE_WITH_EXTENSION = /(?:ext|x|extension)\.?\s*\d+/i;
  static readonly PHONE_INTERNATIONAL = /^\+[\d\s\-]{8,20}$/;
  static readonly PHONE_LOCAL_GENERAL = /^[\d\s\-\(\)]{7,20}$/;
  static readonly PHONE_ISRAELI_LOCAL = /^0\d{1,2}[\-\s]?\d{3}[\-\s]?\d{4}$/;
  static readonly PHONE_NORMALIZE_E164 = /[^\d+]/g;
  static readonly DATE_MM_DD_YYYY = /^\d{1,2}\/\d{1,2}\/\d{2,4}$/;
  static readonly DATE_MM_DD_YYYY_DASH = /^\d{1,2}-\d{1,2}-\d{2,4}$/;
  static readonly DATE_YYYY_MM_DD = /^\d{4}-\d{1,2}-\d{1,2}$/;
  static readonly TIME_AM_PM = /^\d+\s*(AM|PM)$/i;
  static readonly TIME_HH_MM = /^\d{1,2}:\d{2}(:\d{2})?$/;
  static readonly YEAR_ONLY = /^(19|20)\d{2}$/;
  static readonly CSS_PX = /^\d+px$/;
  static readonly CSS_PERCENT = /^\d+%$/;
  static readonly CSS_EM = /^\d+em$/;
  static readonly CSS_REM = /^\d+rem$/;
  static readonly CSS_VH = /^\d+vh$/;
  static readonly CSS_VW = /^\d+vw$/;
  static readonly SCRIPT_TAG = /<script[\s\S]*?<\/script>/gi;
  static readonly STYLE_TAG = /<style[\s\S]*?<\/style>/gi;
  static readonly GOOGLE_MESSAGES_CONVERSATION_NAME = /data-e2e-conversation-name="">([^<]+)<\/span>/g;
  static readonly GOOGLE_MESSAGES_SENDER = /data-e2e-conversation-name="">([^<]+)<\/span>/g;
  static readonly GOOGLE_MESSAGES_MESSAGE = /<mws-conversation-snippet[^>]*>(?:<!-*->)*<span[^>]*dir="auto"[^>]*class="[^"]*ng-star-inserted[^"]*"[^>]*>([\s\S]*?)<\/span>(?:<!-*->)*<\/mws-conversation-snippet>/g;
  static readonly WHATSAPP_MAYBE_NAME = /^Maybe\s+(.+)$/i;
  static readonly WHATSAPP_TILDE_NAME = /^~\s*(.+)$/;
  static readonly WHATSAPP_ROW = /<div[^>]*role="row"[^>]*style="[^"]*z-index: \d+[^"]*"[^>]*>([\s\S]*?)(?=<div[^>]*role="row"|<script)/g;
  static readonly WHATSAPP_CONTACT_TITLE = /<span[^>]*title="([^"]+)"[^>]*class="[^"]*_ao3e[^"]*"[^>]*>/;
  static readonly WHATSAPP_ALL_TITLES = /title="([^"]+)"/g;
  static readonly WHATSAPP_GROUP_SENDER = /<span[^>]*class="[^"]*_ao3e[^"]*"[^>]*>[^<]+<\/span><\/div><\/div><span>:&nbsp;<\/span>/;
  static readonly HIBOB_NAME_WITH_NICKNAME = /^(.+?)\s+(\([^)]+\))\s+(.+?)\s*\(([^)]+@[^)]+)\)$/;
  static readonly HIBOB_NAME_WITH_PARENS_EMAIL = /^(.+?)\s*\(([^)]+@[^)]+)\)$/;
  static readonly HIBOB_NAME_WITH_SPACE_EMAIL = /^(.+?)\s+([^\s]+@[^\s]+)$/;
  static readonly HIBOB_EMAIL_IN_STRING = /([^\s]+@[^\s]+)/;
  static readonly HIBOB_MULTIPLE_SPACES = /\s+/g;
  static readonly ENGLISH_EXTRACTION = /[A-Za-z0-9\s\-'&.]+/g;
  static readonly HEBREW_SEGMENT = /[\u0590-\u05FF\uFB1D-\uFB4F]+/g;

  static createCompanySuffixRegex(suffix: string): RegExp {
    return new RegExp(`\\s*,?\\s*${suffix}\\.?$`, 'gi');
  }
}
