/**
 * Manual company name refactoring mappings and protected suffixes.
 * This file is based on the Final Company Name Refactoring Plan.
 */

export const PROTECTED_SUFFIXES = [
  '.com',
  '.ai',
  '.io',
  '.fm',
  'J.P.',
  'AT&T',
  'eBay',
  'SVT.Jobs',
  'GlassesUSA.com',
];

export const COMPANY_SUFFIXES_TO_REMOVE = [
  'Ltd',
  'Limited',
  'Inc',
  'LLC',
  'Corp',
  'Co',
  'Holdings',
  'Group',
  'Technologies',
  'Systems',
  'Solutions',
  'R&D',
  'International',
];

/**
 * Manual refactor list.
 * Keys are the "cleaned" PascalCase names (with whitespace ignored during matching).
 * Values are the desired display brand names.
 */
export const MANUAL_COMPANY_MAPPINGS: Record<string, string> = {
  YouCCTechnologies: 'YouCC',
  RafaelAdvanced: 'Rafael',
  RafaelAdvancedDefenseSystems: 'Rafael',
  RafaelAdvancedDefenseSystemsCareer: 'Rafael',
  StraussGroup: 'Strauss',
  StraussWater: 'Strauss',
  StraussWaterLtd: 'Strauss',
  Monday: 'Monday.com',
  SodaStreamInternational: 'SodaStream',
  SodastreamInternationalLtd: 'SodaStream',
  'Jobtime.israel': 'Jobtime',
  'InfinityLabsR&D': 'InfinityLabs',
  DecathlonIsrael: 'Decathlon',
  DecathlonInternational: 'Decathlon',
  'Wix.com': 'Wix',
  "AllJobs'": 'AllJobs',
  DatoramaASalesforce: 'Datorama',
  ExperisIsrael: 'Experis',
  'OSRR&D': 'OSR',
  OSREnterprises: 'OSR',
  MorningByGreen: 'Morning',
  'Www.leonid.co.il': 'Leonid',
  AmazonWeb: 'Amazon',
  AmazonWebServicesAws: 'Amazon',
  AWS: 'Amazon',
  DemocratechIsrael: 'Democratech',
  HarelFinance: 'Harel',
  HarelInsurance: 'Harel',
  HarelInsuranceFinance: 'Harel',
  PhoenixFinancial: 'Phoenix',
  PhoenixInvestment: 'Phoenix',
  PhoenixHoldings: 'Phoenix',
  MigdalGroup: 'Migdal',
  MigdalCapital: 'Migdal',
  MigdalCapitalMarkets: 'Migdal',
  TidharGroup: 'Tidhar',
  NishaGroup: 'Nisha',
  'IPcom.co.il': 'IPcom',
  Viz: 'Viz.ai',
  SolarEdgeTechnologies: 'SolarEdge',
  SolaredgeTechnologies: 'SolarEdge',
  GlassesUSA: 'GlassesUSA.com',
  GOLFGROUP: 'GolfGroup',
  HMS: 'HMS',
  Hms: 'HMS',
  MercantileDiscount: 'DiscountBank',
  MercantileDiscountBankLtd: 'DiscountBank',
  AgoraRE: 'Agora',
  DentsuIsrael: 'Dentsu',
  PartnerIsrael: 'Partner',
  PartnerCommunications: 'Partner',
  HackerUThriveDX: 'ThriveDX',
  DellTechnologies: 'Dell',
  'MatrixR&D': 'Matrix',
  MatrixRDServices: 'Matrix',
  QualitestIsrael: 'Qualitest',
  EToro: 'eToro',
  'AbraR&D': 'Abra',
  AbraRDSolutionsFormerlyDevalore: 'Abra',
  NestléNespresso: 'Nestlé',
  'Investing.com': 'Investing.com',
  Investingcom: 'Investing.com',
  '3DPrinter': '3DPrinter',
  '3dPrinter': '3DPrinter',
  BrainerHub: 'BrainerHub',
  NetafimIsrael: 'Netafim',
  IntuitiveIsrael: 'Intuitive',
  PagayaGlobal: 'Papaya',
  PAGAYA: 'Papaya',
  Pagaya: 'Papaya',
  Shift4Europe: 'Shift4',
  SVTJobs: 'SVT.Jobs',
  'Svt.jobsRecruitment': 'SVT.Jobs',
  TomerAGovernment: 'Tomer',
  Mend: 'Mend.io',
  AkamaiTechnologies: 'Akamai',
  'Anyclip.com': 'Anyclip',
  COMBLACK: 'Comblack',
  EBay: 'eBay',
  RemitlyIsrael: 'Remitly',
  RemitlyIsraelFormerlyRewire: 'Remitly',
  BUYMETechnologies: 'BUYME',
  TevaPharmaceuticals: 'Teva',
  TevaPharmaceuticalIndustries: 'Teva',
  TevaActivePharmaceuticalIngredients: 'Teva',
  MALAM: 'MalamTeam',
  MertensHoffmanMalamTeam: 'MalamTeam',
  ZIMIntegrated: 'ZIM',
  ZimIntegratedShippingServices: 'ZIM',
  Riverside: 'Riverside.fm',
  REEAutomotive: 'REE',
  MaofMe: 'Maof',
  MaofHR: 'Maof',
  MaofGroup: 'Maof',
  ShebaTel: 'ShebaMedical',
  PwCIsrael: 'PwC',
  KPMGIsrael: 'KPMG',
  SQLinkGroup: 'SQLink',
  'AT&TIsrael': 'AT&T',
  CybereasonALevelBlue: 'Cybereason',
  'HH+ByIlan': 'HH+',
  MamdaIDF: 'IDF',
  'J.P': 'J.P. Morgan',
  EShop: 'eShop',
  NICE: 'NICE',
  NiceLtd: 'NICE',
  NICEActimize: 'NICE',
  EricssonGlobal: 'Ericsson',
  TheCenter: 'CET',
  CompieTechnologies: 'Compie',
  CompiePro: 'Compie',
  InvencoByGVR: 'Invenco',
  Unit9900: 'IDF',
  Unit8200: 'IDF',
  CalIsrael: 'Cal',
  Cal: 'Cal',
  CheckPointSoftware: 'CheckPoint',
  CheckPointSoftwareTechnologiesLtd: 'CheckPoint',
  IaiIsraelAerospaceIndustries: 'IAI',
  IsraelAerospaceIndustries: 'IAI',
  Iai: 'IAI',
  ElAlIsraelAirlines: 'ElAl',
  IecIsraelElectricCorporation: 'IEC',
  IsraelElectricCorporation: 'IEC',
  ClalitHealthServices: 'Clalit',
  ClalitInnovation: 'Clalit',
  ClalitITDigitalDivision: 'Clalit',
  MaccabiHealthCareServices: 'Maccabi',
  MaccabiHealth: 'Maccabi',
  MaccabiHealthcare: 'Maccabi',
  BankHapoalim: 'BankHapoalim',
  BankHapoalimTechnologyDivision: 'BankHapoalim',
  BankLeumi: 'BankLeumi',
  IntelCorporation: 'Intel',
  IntelIsrael: 'Intel',
  IclGroup: 'ICL',
  BdoIsrael: 'BDO',
  MenoraMivtachimGroup: 'Menora',
  HewlettPackardEnterprise: 'HPE',
  NessTechnologies: 'Ness',
  CyberArkSoftware: 'CyberArk',
  AmdocsIsrael: 'Amdocs',
  NvidiaIsrael: 'NVIDIA',
  MetaIsrael: 'Meta',
  GoogleIsrael: 'Google',
  MicrosoftIsrael: 'Microsoft',
  'MicrosoftR&D': 'Microsoft',
  AccentureArgentina: 'Accenture',
  AppliedMaterialsIsrael: 'AppliedMaterials',
  PaloAltoNetworks: 'PaloAlto',
  SamsungResearchIsrael: 'Samsung',
  TelAvivUniversity: 'TAU',
  BenGurionUniversity: 'BGU',
  Isracard: 'Isracard',
  LeumitHealthServices: 'Leumit',
  LeumitGroup: 'Leumit',
  Meuhedet: 'Meuhedet',
  IsraelRailways: 'IsraelRailways',
  IsraelPolice: 'IsraelPolice',
  MinistryOfHealth: 'MOH',
  JFrog: 'JFrog',
  HOT: 'HOT',
  HOTmobile: 'HOT',
  Cellcom: 'Cellcom',
  Bezeq: 'Bezeq',
  Shufersal: 'Shufersal',
  Osem: 'Osem',
  OsemNestle: 'Osem',
  Tempo: 'Tempo',
  TempoBeverages: 'Tempo',
  BankMizrahiTefahot: 'BankMizrahiTefahot',
  BankOtsarHaHayal: 'BankOtsarHaHayal',
  OtsarHaHayal: 'BankOtsarHaHayal',
  BankOfIsrael: 'BankOfIsrael',
  Payoneer: 'Payoneer',
  Playtika: 'Playtika',
  Taboola: 'Taboola',
  WalkMe: 'WalkMe',
  Zerto: 'Zerto',
  Osr: 'OSR',
  OSR: 'OSR',
  Mis: 'MIS',
  MIS: 'MIS',
  Anyclip: 'AnyClip',
  AnyClip: 'AnyClip',
  Entrosecurity: 'EntroSecurity',
  EntroSecurity: 'EntroSecurity',
  HR: 'HR',
  Hr: 'HR',
  DunBradstreet: 'Dun & Bradstreet',
  Avif: 'AVIF',
  AVIF: 'AVIF',
  Mcpd: 'MCPD',
  MCPD: 'MCPD',
  Jumbomail: 'JUMBOMail',
  JumboMail: 'JUMBOMail',
  Similarweb: 'Similarweb',
};
